security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: 
            memory:
                    users:
                        ezequiel:
                            password: 4739
                            roles: 'ROLE_USER'
                        admin:
                            password: 1234
                            roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

    # config/packages/security.yaml
    access_control:
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/actividades/listaActividadesAjax, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST, GET] }
